DROP TABLE Tab;
DROP TABLE Pedidos;
DROP TABLE Prod;
DROP TABLE Price;

CREATE TABLE Tab (
id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
tabname varchar(254) NOT NULL,
tabdet varchar(254),
status varchar(1) NOT NULL,
op_date DATETIME NOT NULL,
cl_date DATETIME
);

CREATE TABLE Pedidos (
id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
tabid INT(7) NOT NULL,
tabdet varchar(254),
prod VARCHAR(30) NOT NULL,
proddet VARCHAR(254),
qty int(2) NOT NULL,
price DOUBLE(10,2) NOT NULL,
status varchar(1),
op_date DATETIME NOT NULL,
cl_date DATETIME NOT NULL
);

CREATE TABLE Prod (
id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
prod VARCHAR(30) NOT NULL,
proddet VARCHAR(10000),
tipo VARCHAR(20) NOT NULL,
status varchar(1) NOT NULL,
op_date DATETIME NOT NULL
);

CREATE TABLE Price (
id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
prod VARCHAR(30) NOT NULL,
price DOUBLE(10,2) NOT NULL,
op_date DATETIME NOT NULL
);

CREATE TABLE Transkey (
id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
orig VARCHAR(30) NOT NULL,
unikey DOUBLE(10,2) NOT NULL,
op_date DATETIME NOT NULL
);